steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install', '-f', './complete/pom.xml']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/docker-example', './complete/' ]
- name: gcr.io/cloud-builders/docker
  args: ['tag',
         'gcr.io/$PROJECT_ID/docker-example',
         'gcr.io/$PROJECT_ID/docker-example:v1']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/docker-example:v1']
- name: gcr.io/cloud-builders/docker
  args: ['run', 'gcr.io/$PROJECT_ID/docker-example:v1']
images:
- 'gcr.io/$PROJECT_ID/docker-example:v1'